---
- name: Configure NTP with Chrony
  block:
    - name: Ensure Chrony is installed
      ansible.builtin.package:
        name: chrony
        state: present
    - name: Configure Chrony NTP servers
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Chrony service
    - name: Ensure Chrony service is enabled and running
      ansible.builtin.systemd:
        name: chronyd
        enabled: true
        state: started
