---
# handlers file for ./system_baseline/roles/system_base_settings
- name: Update locale
  ansible.builtin.command: update-locale
  changed_when: true
- name: Restart Chrony service
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
